# Generated by Django 6.0.2 on 2026-02-17 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maqola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maqola',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maqolalar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maqola',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqola.category'),
        ),
        migrations.AddField(
            model_name='like',
            name='maqola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqola.maqola'),
        ),
        migrations.AddField(
            model_name='comment',
            name='maqola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqola.maqola'),
        ),
    ]
