# Generated by Django 6.0.2 on 2026-02-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
