# Generated by Django 6.0.2 on 2026-02-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0002_maqola_author_alter_comment_adminreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='comment'),
            preserve_default=False,
        ),
    ]
